development:
bucket: webtutor2
access_key_id: AKIAIIZK4QIVR7LYFLIA
secret_access_key: 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
test:
bucket: webtutor2
access_key_id: AKIAIIZK4QIVR7LYFLIA
secret_access_key: 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
production:
bucket: webtutor2
access_key_id: AKIAIIZK4QIVR7LYFLIA
secret_access_key: 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
