development:
bucket: webtutor2
access_key_id: 
secret_access_key: 
test:
bucket: webtutor2
access_key_id: 
secret_access_key: 
production:
bucket: webtutor2
access_key_id: 
secret_access_key: 

ALL PAST KEYS DELETED. None will work! CREATE YOUR OWN AMAZON SW account to use this feature!
