require 'spec_helper'
require 'factory_girl_rails'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsersController do
include AuthHelper
before(:each) do
http_login
end
  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "first_name" => "MyString", "last_name" => "dsadsad", "username" => "yoaa221", "password" => "PaSs123K", "user_role" => "student" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all users as @users" do
      user = User.new
user.first_name = "MyString"
user.last_name = "MyString"
user.username = "yo"
user.password = "PaSs789K"
user.user_role = "student"
user.save
      get :index, {}, valid_session
      assigns(:users).should eq([user])
    end
  end


   describe "GET show" do
    it "assigns the requested user as @user" do
           user = User.new
user.first_name = "MyString"
user.username = "yo"
user.password = "PaSs789K"
user.save
      get :show, {:id => user.to_param}, valid_session
      assigns(:user).should eq(user)
    end
  end

  describe "GET new" do
    it "assigns a new user as @user" do
  @request.env["HTTP_AUTHORIZATION"] = "Basic " + Base64::encode64("username:password")
      get :new, {}, valid_session
      assigns(:user).should be_a_new(User)
    end
  end

  describe "GET edit" do
    it "assigns the requested user as @user" do
            user = User.new
user.first_name = "MyString"
user.last_name = "ddd"
user.username = "yo"
user.password = "PaSs789K"
user.save
      get :edit, {:id => user.to_param}, valid_session
      assigns(:user).should eq(user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new User" do
        expect {
          post :create, {:user => { "first_name" => "MyStddring", "last_name" => "dsadsad", "username" => "yoaa221", "password" => "PaSs123K" }}, valid_session
        }.to change(User, :count).by(1)
      end

      it "assigns a newly created user as @user" do
        post :create, {:user => { "first_name" => "MyString", "last_name" => "dsadsad", "username" => "yoaa221", "password" => "PaSs123K" }}, valid_session
        assigns(:user).should be_a(User)
        assigns(:user).should be_persisted
      end

      it "redirects to the log in page" do
        post :create, {:user => { "first_name" => "MyString", "last_name" => "dsadsad", "username" => "yoaa221", "password" => "PaSs123K" }}, valid_session
        response.should redirect_to('/access/login')
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user as @user" do
        # Trigger the behavior that occurs when invalid params are submitted
        User.any_instance.stub(:save).and_return(false)
        post :create, {:user => { "first_name" => "invalid value" }}, valid_session
        assigns(:user).should be_a_new(User)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        User.any_instance.stub(:save).and_return(false)
        post :create, {:user => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end
describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user" do
             user = User.new
user.first_name = "MyString"
user.last_name = "ddd"
user.username = "yo"
user.password = "PaSs789K"
user.save
        # Assuming there are no other users in the database, this
        # specifies that the User created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        User.any_instance.should_receive(:update_attributes).with({ "first_name" => "MyString", "last_name" => "ddd", "username" => "yoaa221", "password" => "PaSs123K" })
        put :update, {:id => user.to_param, :user => { "first_name" => "MyString", "last_name" => "ddd", "username" => "yoaa221", "password" => "PaSs123K" }}, valid_session
      end

      it "assigns the requested user as @user" do
              user = User.new
user.first_name = "MyString"
user.last_name = "ddd"
user.username = "yo"
user.password = "PaSs789K"
user.save
        put :update, {:id => user.to_param, :user => { "first_name" => "MyString", "last_name" => "ddd", "username" => "yoaa221", "password" => "PaSs123K" }}, valid_session
        assigns(:user).should eq(user)
      end

      it "redirects to the home" do
              user = User.new
user.first_name = "MyString"
user.last_name = "ddd"
user.username = "yo"
user.password = "PaSs789K"
user.save
        put :update, {:id => user.to_param, :user => { "first_name" => "MyString", "last_name" => "ddd", "username" => "yoaa221", "password" => "PaSs123K" }}, valid_session
        response.should redirect_to('/home')
      end


    end

    describe "with invalid params" do
      it "assigns the user as @user" do
             user = User.new
user.first_name = "MyString"
user.last_name = "ddd"
user.username = "yo"
user.password = "PaSs789K"
user.save
        # Trigger the behavior that occurs when invalid params are submitted
        User.any_instance.stub(:save).and_return(false)
        put :update, {:id => user.to_param, :user => { "first_name" => "invalid value" }}, valid_session
        assigns(:user).should eq(user)
      end

      it "re-renders the 'edit' template" do
              user = User.new
user.first_name = "MyString"
user.last_name = "ddd"
user.username = "yo"
user.password = "PaSs789K"
user.save
        # Trigger the behavior that occurs when invalid params are submitted
        User.any_instance.stub(:save).and_return(false)
        put :update, {:id => user.to_param, :user => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user" do
           bah = User.new
bah.first_name = "MyString"
bah.username = "yo"
bah.user_role = "owner"
bah.password = "PaSs789K"
bah.last_name = "dsadsad"
bah.created_at = Time.now

bah.save
      expect {
        delete :destroy, {:id => bah.to_param}, valid_session
      }.to change(User, :count).by(-1)
    end

    it "redirects to the users list" do
            use = User.new
use.first_name = "MyString"
use.username = "yo"
use.password = "PaSs789K"
use.last_name = "dsadsad"
use.user_role = "owner"
use.created_at = Time.now
use.subscribtion_expire = Time.now + (2*7*24*60*60)
use.save
      delete :destroy, {:id => use.to_param}, valid_session
      response.should redirect_to('/access/login')
    end
  end

 
end
